#!/usr/bin/env python3
"""Generate the built-in CA trust stores from the Mozilla root bundle.

    python tools/gencertstore.py                       # fetch the current bundle
    python tools/gencertstore.py --bundle cacert.pem   # use a local copy

Writes two headers of DER certificate data next to the TLS library:

    libraries/EthernetClientSecure/src/ca_roots_minimal.h
    libraries/EthernetClientSecure/src/ca_roots_full.h

WHY GENERATED AND COMMITTED. Roots expire and get distrusted, so the list has
to be refreshable by one command; and a build must never need the network,
so the output is committed. That is the same arrangement tools/genvariants.py
uses for the pin tables.

Checking rather than trusting memory matters here. Four roots that any list
written from experience would include -- DigiCert Global Root CA, Baltimore
CyberTrust Root, GlobalSign Root CA and AAA Certificate Services -- are no
longer in the Mozilla store at all. A hand-maintained header would still name
them, and a sketch relying on one would fail against a server that had moved
on.

WHY DER AND NOT PEM. PEM is base64, so it costs a third more flash for the
same bytes, and mbedtls has to decode it before parsing. The store is read by
a callback that parses one root per handshake, so DER is both smaller and the
form it is wanted in.

THE MINIMAL SET IS MEASURED, NOT GUESSED. Every root in it is either one a
real station's chain was observed to need, or one of the general-purpose roots
that the APIs a sketch is likely to call chain to. The stations were probed
with openssl and their chains recorded; see MINIMAL below.
"""
import argparse
import base64
import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "libraries" / "EthernetClientSecure" / "src"
BUNDLE_URL = "https://curl.se/ca/cacert.pem"

# The minimal store.
#
# The first group is not a judgement call: each was taken from the chain a
# real station actually presented, read off with
#
#     openssl s_client -showcerts -connect <host>:443 -servername <host>
#
#   ISRG Root X1          stream.laut.fm, icecast.omroep.nl, www.radio.net
#   USERTrust RSA         stream.antenne.de, ice1.somafm.com, api.github.com
#   Go Daddy Root G2      stream.srg-ssr.ch
#
# The ECC siblings come with them because a server may present either, and the
# rest are the general-purpose roots behind most APIs and CDNs. Anything not
# in the current Mozilla bundle is reported rather than silently skipped.
MINIMAL = [
    "ISRG Root X1",
    "ISRG Root X2",
    "USERTrust RSA Certification Authority",
    "USERTrust ECC Certification Authority",
    "Go Daddy Root Certificate Authority - G2",
    "DigiCert Global Root G2",
    "DigiCert Global Root G3",
    "DigiCert High Assurance EV Root CA",
    "GlobalSign Root CA - R3",
    "GlobalSign Root CA - R6",
    "GlobalSign ECC Root CA - R5",
    "Amazon Root CA 1",
    "Amazon Root CA 2",
    "Amazon Root CA 3",
    "Amazon Root CA 4",
    "Certum Trusted Network CA",
]


def load_bundle(path):
    text = path.read_text(encoding="utf-8", errors="replace")
    out = []
    for label, pem in re.findall(
            r"\n([^\n=]+)\n=+\n(-----BEGIN CERTIFICATE-----.*?"
            r"-----END CERTIFICATE-----)", text, re.S):
        body = re.search(r"-----BEGIN CERTIFICATE-----(.*?)"
                         r"-----END CERTIFICATE-----", pem, re.S).group(1)
        out.append((label.strip(), base64.b64decode("".join(body.split()))))
    return out


def c_identifier(name):
    return "ca_" + re.sub(r"[^0-9a-zA-Z]+", "_", name).strip("_").lower()


def subject_der(der):
    """The certificate's subject name, DER encoded.

    This is what mbedtls calls subject_raw, and what a child's issuer_raw is
    compared against. Taken with a real X.509 parser rather than by walking
    the ASN.1 here: getting it subtly wrong would not fail the build, it would
    fail to match a root at handshake time.
    """
    try:
        from cryptography import x509
    except ImportError:
        sys.exit("this needs the cryptography module: pip install cryptography")
    return x509.load_der_x509_certificate(der).subject.public_bytes()


def emit(path, name, certs, note):
    lines = ['''/* %(title)s -- GENERATED by tools/gencertstore.py. Do not edit.
 *
 * %(note)s
 *
 * %(count)d roots, %(bytes)d bytes of DER.
 *
 * Each entry is a root certificate in DER form. CATrustStore.cpp hands these
 * to mbedtls one at a time, parsing only the one whose subject matches the
 * server's issuer, so the size below is flash and not RAM.
 */
#pragma once

#include <stddef.h>
#include <stdint.h>
''' % {
        "title": name,
        "note": note,
        "count": len(certs),
        "bytes": sum(len(d) for d in certs),
    }]

    def blob(ident, data):
        lines.append("static const uint8_t %s[] = {" % ident)
        for i in range(0, len(data), 12):
            lines.append("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
        lines.append("};")

    for label, der in certs:
        ident = c_identifier(label)
        lines.append("/* %s (%d bytes) */" % (label, len(der)))
        blob(ident, der)
        # The subject name, DER encoded, so the lookup can compare it against
        # a child's issuer_raw with a memcmp and parse only the root that
        # matches. Without this the callback would have to parse all 121 roots
        # on every handshake to find out which one to use.
        blob(ident + "_subject", subject_der(der))
        lines.append("")

    lines.append("static const ch32h4_ca_entry_t CH32H4_CA_ROOTS[] = {")
    for label, der in certs:
        ident = c_identifier(label)
        lines.append('    { %s, sizeof(%s), %s_subject, sizeof(%s_subject) },'
                     % (ident, ident, ident, ident))
        lines.append('    /* %s */' % label)
    lines.append("};")
    lines.append("")
    lines.append("static const size_t CH32H4_CA_ROOT_COUNT =")
    lines.append("    sizeof(CH32H4_CA_ROOTS) / sizeof(CH32H4_CA_ROOTS[0]);")
    # UTF-8 explicitly: at least one root's name carries a non-ASCII character
    # (a Hungarian CA), and the default locale codec on Windows cannot encode
    # it -- which failed the write half way through the full store.
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", help="a local cacert.pem instead of fetching")
    args = ap.parse_args()

    if args.bundle:
        bundle = pathlib.Path(args.bundle)
    else:
        bundle = pathlib.Path(__file__).with_name("cacert.pem.tmp")
        print("fetching %s" % BUNDLE_URL)
        with urllib.request.urlopen(BUNDLE_URL, timeout=60) as r:
            bundle.write_bytes(r.read())

    all_certs = load_bundle(bundle)
    if len(all_certs) < 50:
        sys.exit("only %d roots parsed from %s -- wrong file?"
                 % (len(all_certs), bundle))
    by_name = dict(all_certs)

    minimal = []
    missing = []
    for want in MINIMAL:
        if want in by_name:
            minimal.append((want, by_name[want]))
        else:
            missing.append(want)
    if missing:
        print("NOT in the current bundle, so left out:")
        for m in missing:
            print("   %s" % m)

    emit(OUT_DIR / "ca_roots_minimal.h", "Minimal CA trust store", minimal,
         "The roots real stations were observed to need, plus the "
         "general-purpose ones most APIs chain to.")
    emit(OUT_DIR / "ca_roots_full.h", "Full CA trust store", all_certs,
         "Every root in the Mozilla store, as shipped by curl.se.")

    for label, certs in (("minimal", minimal), ("full", all_certs)):
        print("%-8s %3d roots, %6d bytes DER (%.1f KB)"
              % (label, len(certs), sum(len(d) for _n, d in certs),
                 sum(len(d) for _n, d in certs) / 1024))

    if not args.bundle:
        bundle.unlink()


if __name__ == "__main__":
    main()
