#!/usr/bin/env python3
"""Generate boards.txt.

Run it after editing the tables below and commit the result:

    python tools/makeboards.py

boards.txt is generated rather than written by hand for the same reason
arduino-pico generates its own: the Filesystem menu is one stanza repeated per
size, each carrying a byte count and a maximum sketch size that have to agree
with the flash layout, and a hand-maintained list of those is a list of numbers
that will eventually disagree with the linker script. Here the sizes come from
one table and the sketch size is computed, so an entry cannot be individually
wrong.

The generated file IS committed. The Arduino IDE and the boards manager read
boards.txt directly and never run this, so a checkout that has not run it must
still build.
"""
import io
import os
import sys

# The flash layout, which is also stated in the variant's linker script and
# asserted there at link time. If these disagree with it the build fails in the
# linker rather than producing a board that overwrites its own filesystem.
USER_FLASH = 960 * 1024        # the whole user area at 0x08000000
V3F_RESERVED = 32 * 1024       # the V3F stub, below the V5F image
EEPROM_SIZE = 16 * 1024        # the EEPROM tail, always present
ERASE_PAGE = 8 * 1024          # erase granularity with DBMODE=1

SKETCH_MAX = USER_FLASH - V3F_RESERVED - EEPROM_SIZE   # with no filesystem

# Filesystem sizes offered. Every one must be a multiple of the erase page --
# a partition that does not start on one cannot be erased without taking a
# neighbour with it -- and must leave room for a sketch.
FS_SIZES = [0, 64 * 1024, 128 * 1024, 256 * 1024, 512 * 1024]

BOARDS = [
    {
        "id": "ch32h417qeu6",
        "name": "CH32H417QEU6-R0-1v1",
        "variant": "CH32H417QEU6",
        "mcu": "ch32h417qeu6",
        "f_cpu": "400000000L",
        "board": "CH32H417QEU6",
        "march": "rv32imafc_zba_zbb_zbc_zbs_xw",
        "mabi": "ilp32f",
        # SYSCLK 400 MHz from the 25 MHz crystal: V5F at 400, V3F at 100.
        #
        # Not a menu, because there is only one supported entry. The SDK offers
        # HSI variants of each tree, but ch32h4_clock_is_nominal() requires HSE
        # -- USB and Ethernet need a clock the internal RC cannot hold -- so an
        # HSI build boots straight into the console's degraded-clock warning.
        # The 480 MHz trees put the V3F at 120 MHz, which CH32H4_EXPECTED_HCLK
        # in ch32h4_clock.c does not follow.
        "clock": "SYSCLK_400M_CoreCLK_V5F_400M_V3F_100M_HSE=400000000",
        # The register description the debugger reads, from debug/.
        "svd": "CH32H417xx.svd",
        # 128 KB of the 320 KB SRAM belongs to the V5F's heap; this is what the
        # IDE reports a sketch's RAM against.
        "data_size": 917504,
        # Which size the Filesystem menu starts on. 128 KB leaves 656 KB for a
        # sketch, which no sketch built with this core has come close to.
        "default_fs": 128 * 1024,
    },
]

HEADER = """# Arduino IDE board definitions for the CH32H41x.
#
# GENERATED BY tools/makeboards.py -- edit that and re-run it, not this file.
#
# PlatformIO does not read this: it uses the board JSON in platform-ch32v and
# tools/platformio-build.py. The two are two statements of the same build, and
# the flash layout in both comes from the same numbers.

menu.serial=Serial port
menu.exceptions=C++ Exceptions
menu.fs=Filesystem size
"""

EXCEPTIONS = """
# Off by default, as in arduino-pico and the ESP cores. Enabling costs roughly
# 30 KB of unwind tables, which stay in flash and are read only when something
# throws.
#
# NOTE: --specs=nano.specs must never be added to make up the difference. It
# rewrites -lstdc++ to -lstdc++_nano, which has no .eh_frame, and every throw
# then reaches std::terminate -- after a perfectly clean link, with the failure
# visible only at run time.
{id}.menu.exceptions.Disabled=Disabled
{id}.menu.exceptions.Disabled.build.flags.exceptions=-fno-exceptions
{id}.menu.exceptions.Disabled.build.flags.exceptions.define=
{id}.menu.exceptions.Enabled=Enabled
{id}.menu.exceptions.Enabled.build.flags.exceptions=-fexceptions
{id}.menu.exceptions.Enabled.build.flags.exceptions.define=-DCH32H4_EXCEPTIONS
"""

SERIAL = """
# What `Serial` refers to. Serial1 is always USART1 on PA9/PA10, into the
# WCH-Link's VCP, whichever is chosen here.
#
# USB CDC is the default, as in the PlatformIO build, because it is what
# someone plugging the board into a PC expects to find. The sketch does not
# have to include Adafruit_TinyUSB.h: the library is pulled in by Arduino.h's
# own include of it, which fails during arduino-cli's library-detection pass
# because platform.txt deliberately holds the TinyUSB headers back from that
# pass -- see build.includes.detect there, which explains why an include path
# that resolves too early is the thing that breaks this.
#
# The USART1 option is worth keeping: a fault during static initialisation
# happens before USB has enumerated, so a board that only speaks CDC cannot
# report one.
{id}.menu.serial.usb=USB CDC
{id}.menu.serial.usb.build.flags.serial=-DCH32H4_USB -DUSE_TINYUSB -DCH32H4_SERIAL_IS_USB
{id}.menu.serial.uart=USART1
{id}.menu.serial.uart.build.flags.serial=
"""

FS_INTRO = """
# The filesystem partition, immediately below the 16 KB EEPROM at the top of
# flash. LittleFS mounts it; tools/simplesub.py substitutes the size into the
# linker script, which then ASSERTs that the sketch region, the filesystem and
# the EEPROM tile the {user}-byte user area exactly.
#
# The EEPROM is NOT part of this menu. It is always present and always the last
# {eeprom} bytes, so that a sketch's stored settings survive a change of
# filesystem size -- which arduino-pico does the same way and for the same
# reason.
"""


def human(size):
    if size == 0:
        return "None"
    if size % (1024 * 1024) == 0:
        return "%d MB" % (size // (1024 * 1024))
    return "%d KB" % (size // 1024)


def generate():
    out = [HEADER]

    for b in BOARDS:
        i = b["id"]
        out.append("\n" + "# " + "-" * 74 + "\n# %s\n# " % b["name"] + "-" * 74 + "\n")
        out.append(
            "{id}.name={name}\n"
            "{id}.build.core=ch32h4\n"
            "{id}.build.variant={variant}\n"
            "{id}.build.mcu={mcu}\n"
            "{id}.build.f_cpu={f_cpu}\n"
            "{id}.build.board={board}\n"
            "{id}.build.march={march}\n"
            "{id}.build.mabi={mabi}\n"
            "{id}.build.flags.clock=-D{clock}\n"
            "{id}.build.svd={svd}\n"
            "{id}.upload.tool=wlink\n"
            "{id}.upload.maximum_data_size={data}\n".format(
                id=i, name=b["name"], variant=b["variant"], mcu=b["mcu"],
                f_cpu=b["f_cpu"], board=b["board"], march=b["march"],
                mabi=b["mabi"], clock=b["clock"], svd=b["svd"],
                data=b["data_size"]))

        out.append(SERIAL.format(id=i))
        out.append(EXCEPTIONS.format(id=i))
        out.append(FS_INTRO.format(user=USER_FLASH, eeprom=EEPROM_SIZE))

        # The board's default goes FIRST. arduino-cli takes the first entry of
        # a menu as the value for an FQBN that does not name one, so the order
        # here is what a bare `arduino-cli compile -b <fqbn>` gets -- the
        # top-level build.fs_size below is not consulted once the menu exists.
        sizes = [b["default_fs"]] + [s for s in FS_SIZES if s != b["default_fs"]]

        for size in sizes:
            if size % ERASE_PAGE:
                sys.stderr.write(
                    "makeboards: %d is not a multiple of the %d-byte erase"
                    " page\n" % (size, ERASE_PAGE))
                return None
            sketch = SKETCH_MAX - size
            if sketch <= 0:
                sys.stderr.write(
                    "makeboards: a %d-byte filesystem leaves no room for a"
                    " sketch\n" % size)
                return None
            key = "%dk" % (size // 1024)
            out.append(
                "{id}.menu.fs.{key}={label}\n"
                "{id}.menu.fs.{key}.build.fs_size={size}\n"
                "{id}.menu.fs.{key}.upload.maximum_size={sketch}\n".format(
                    id=i, key=key, label=human(size), size=size, sketch=sketch))

        # Stated outside the menu as well, so that reading boards.txt shows
        # what the board's size is without working out which entry comes first.
        out.append(
            "\n{id}.build.fs_size={size}\n"
            "{id}.upload.maximum_size={sketch}\n".format(
                id=i, size=b["default_fs"],
                sketch=SKETCH_MAX - b["default_fs"]))

    return "".join(out)


def main():
    text = generate()
    if text is None:
        return 1
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir,
                        "boards.txt")
    path = os.path.normpath(path)
    with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    sys.stdout.write("wrote %s\n" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
