"""Turn an MP3 into a C array so the decoder test needs no filesystem.

The board and the pytest HTTP server must serve byte-identical data, so both
come from tests/data/tone.mp3 and a test asserts the checksums agree.
"""
import pathlib
import sys


def main(src, dst, name):
    data = pathlib.Path(src).read_bytes()
    lines = [
        "/* GENERATED by tools/mp3_to_header.py from %s -- do not edit. */"
        % pathlib.Path(src).name,
        "#pragma once",
        "#include <stdint.h>",
        "",
        "static const uint32_t %s_len = %d;" % (name, len(data)),
        "static const uint8_t %s[] = {" % name,
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + " ".join("0x%02X," % b for b in data[i:i + 16]))
    lines += ["};", ""]
    pathlib.Path(dst).write_text("\n".join(lines))
    print("%s: %d bytes" % (dst, len(data)))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
