#!/usr/bin/env python3
"""Turn PEM files into a C header of string literals.

    pem_to_header.py --out certs.h name=file.crt [name=file.key ...]

Each PEM becomes `static const char name[] = "...";`, one C string per line
with an explicit newline, because mbedtls parses PEM by looking for the
BEGIN/END lines and a chain joined without newlines is not a chain.

Written for the test certificates, but it is the same job anyone embedding a
CA bundle has, so it lives in tools/ rather than in the test directory.
"""
import argparse
import os
import sys


def literal(path):
    with open(path, "r", encoding="ascii") as f:
        text = f.read()
    # Normalise: CRLF in a PEM is legal but makes the generated header depend
    # on how git checked the file out.
    lines = text.replace("\r\n", "\n").strip("\n").split("\n")
    out = []
    for line in lines:
        if '"' in line or "\\" in line:
            raise SystemExit("%s: PEM contains a quote or backslash" % path)
        out.append('    "%s\\n"' % line)
    return "\n".join(out)


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("pairs", nargs="+", metavar="name=file")
    args = ap.parse_args(argv)

    chunks = ["/* Generated by tools/pem_to_header.py. Do not edit. */",
              "#pragma once", ""]
    for pair in args.pairs:
        if "=" not in pair:
            raise SystemExit("expected name=file, got %r" % pair)
        name, path = pair.split("=", 1)
        chunks.append("static const char %s[] =" % name)
        chunks.append(literal(path) + ";")
        chunks.append("")

    out = "\n".join(chunks)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".",
                exist_ok=True)
    with open(args.out, "w", encoding="ascii", newline="\n") as f:
        f.write(out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
